version: 2
updates:
  - package-ecosystem: pip
    directory: /mcp-cmr24
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
